name: Update Gold Price

on:
  schedule:
    - cron: '0 * * * *' # Runs automatically every hour
  workflow_dispatch: # Allows you to run it manually anytime from GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 firebase-admin

      - name: Run script
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: python scraper.py
        
